from __future__ import annotations

"""Laser acceleration (LWFA-style) input generation.

This is the next simulation family after uniform_plasma.

Scope goal (first iteration):
- generate a PICMI script for a simple 2D LWFA-like setup
- validation: schema + a few basic physics/numerics sanity checks

We intentionally start with PICMI generation only, because the native inputs
surface for lasers is broad and more error-prone.
"""

from dataclasses import asdict, dataclass, field
from textwrap import dedent
from typing import List, Optional


@dataclass
class LaserAccelerationSpec:
    name: str = "laser_acceleration"

    # Geometry
    dim: int = 2
    number_of_cells: List[int] = field(default_factory=lambda: [128, 512])
    lower_bound: List[float] = field(default_factory=lambda: [-20e-6, 0.0])
    upper_bound: List[float] = field(default_factory=lambda: [20e-6, 200e-6])
    field_bc: List[str] = field(default_factory=lambda: ["periodic", "open"])

    # Time
    max_steps: int = 200
    cfl: float = 0.99

    # Plasma
    plasma_density: float = 1.0e24  # m^-3
    plasma_zmin: float = 20e-6
    plasma_zmax: float = 180e-6

    # Laser
    wavelength: float = 0.8e-6
    a0: float = 2.0
    waist: float = 15e-6
    duration: float = 30e-15
    focal_position_z: float = 60e-6
    centroid_position_z: float = 0.0

    # Numerics
    particle_shape: str = "linear"

    # Diagnostics
    diag_period: int = 50
    diag_fields: List[str] = field(default_factory=lambda: ["Ex", "Ey", "Ez", "Bx", "By", "Bz"])


def generate_picmi_laser_acceleration(spec: LaserAccelerationSpec) -> str:
    """Generate a PICMI script for a simple laser acceleration setup."""

    if spec.dim != 2:
        raise ValueError("First iteration supports dim=2 only")

    d = asdict(spec)

    script = f"""#!/usr/bin/env python3

# Auto-generated by warpx-inputgen.
# Make source-tree runs work without requiring `pip install warpx`.
import os
import sys
import glob

_this_repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir, os.pardir, os.pardir))
_pywarpx_src = os.path.join(_this_repo_root, "Python")
if _pywarpx_src not in sys.path:
    sys.path.insert(0, _pywarpx_src)

# Ensure ADIOS2 runtime libs are discoverable on systems where the WarpX
# Python extensions are linked against libadios2_cxx11.so.
# This is a best-effort helper for Aurora-like module environments.
_adios2_libdir = os.environ.get("ADIOS2_LIBDIR", "")
if not _adios2_libdir:
    # Common Aurora spack layout
    _cands = []
    for _p in glob.glob(
        "/opt/aurora/25.190.0/spack/unified/*/install/**/adios2*/lib64/libadios2_cxx11.so.2.10",
        recursive=True,
    )[:5]:
        _cands.append(os.path.dirname(_p))
    if _cands:
        _adios2_libdir = _cands[0]

if _adios2_libdir:
    os.environ["LD_LIBRARY_PATH"] = _adios2_libdir + (
        ":" + os.environ["LD_LIBRARY_PATH"] if os.environ.get("LD_LIBRARY_PATH") else ""
    )

from pywarpx import picmi

c = picmi.constants.c

SPEC = {d!r}

grid = picmi.Cartesian2DGrid(
    number_of_cells={spec.number_of_cells!r},
    lower_bound={spec.lower_bound!r},
    upper_bound={spec.upper_bound!r},
    lower_boundary_conditions={spec.field_bc!r},
    upper_boundary_conditions={spec.field_bc!r},
)

solver = picmi.ElectromagneticSolver(grid=grid, method="CKC", cfl={spec.cfl!r})

# Plasma
plasma_dist = picmi.UniformDistribution(
    density={spec.plasma_density!r},
    lower_bound=[None, None, {spec.plasma_zmin!r}],
    upper_bound=[None, None, {spec.plasma_zmax!r}],
    fill_in=True,
)

electrons = picmi.Species(particle_type="electron", name="electrons", initial_distribution=plasma_dist)
ions = picmi.Species(
    particle_type="H",
    name="ions",
    charge_state=1,
    initial_distribution=plasma_dist,
)

# Laser
laser = picmi.GaussianLaser(
    wavelength={spec.wavelength!r},
    waist={spec.waist!r},
    duration={spec.duration!r},
    focal_position=[0.0, 0.0, {spec.focal_position_z!r}],
    centroid_position=[0.0, 0.0, {spec.centroid_position_z!r}],
    propagation_direction=[0, 0, 1],
    polarization_direction=[1, 0, 0],
    a0={spec.a0!r},
    fill_in=False,
)

# Place the antenna slightly inside the domain so it's not outside due to
# floating point edge comparisons.
_antenna_z = {spec.lower_bound[1]!r} + 1.0e-12
antenna = picmi.LaserAntenna(position=[0.0, 0.0, _antenna_z], normal_vector=[0, 0, 1])

# Disable full field diagnostics by default in this minimal template.
# Plotfile writing from multiple MPI ranks can fail if the output directory is
# shared/contended or pre-exists from a previous run.
#
# Re-enable by adding a FieldDiagnostic and a per-run unique write_dir.
field_diag = None

sim = picmi.Simulation(
    solver=solver,
    max_steps={spec.max_steps!r},
    particle_shape={spec.particle_shape!r},
    warpx_use_filter=0,
)

sim.add_species(electrons, layout=picmi.GriddedLayout(grid=grid, n_macroparticle_per_cell=[2, 2, 2]))
sim.add_species(ions, layout=picmi.GriddedLayout(grid=grid, n_macroparticle_per_cell=[2, 2, 2]))

sim.add_laser(laser, injection_method=antenna)
if field_diag is not None:
    sim.add_diagnostic(field_diag)

sim.initialize_inputs()
sim.initialize_warpx()
sim.step({spec.max_steps!r})
"""

    return dedent(script).lstrip()
