from __future__ import annotations

"""Laser acceleration (LWFA-style) input generation.

This is the next simulation family after uniform_plasma.

Scope:
- generate a PICMI script for a simple 2D or 3D LWFA-like setup
- validation: schema + a few basic physics/numerics sanity checks

The external JSON spec format is flat (dim, max_steps, wavelength, …) for
backward compatibility with borealis-mcp callers.  Internally, the spec is
composed of reusable block dataclasses from blocks.py.
"""

from dataclasses import asdict, dataclass, field
from textwrap import dedent

from .blocks import (
    AMRSpec,
    DiagSpec,
    DomainSpec,
    ImplicitSolverSpec,
    LaserSpec,
    SolverSpec,
    SpeciesSpec,
    _AMR_KEY_MAP,
    suggest_cells,
)

_GRID_CLASS = {2: "Cartesian2DGrid", 3: "Cartesian3DGrid"}

# Keys that belong to each block (used by from_dict)
_DOMAIN_KEYS = {"dim", "number_of_cells", "lower_bound", "upper_bound", "field_bc"}
_SOLVER_KEYS = {"max_steps", "cfl", "particle_shape"}
_SPECIES_KEYS = {"plasma_density", "plasma_zmin", "plasma_zmax"}
_LASER_KEYS = {"wavelength", "a0", "waist", "duration", "focal_position_z",
               "centroid_position_z"}
_DIAG_KEYS     = {"diag_period", "diag_fields"}
_IMPLICIT_KEYS = {"implicit_enabled", "implicit_theta", "implicit_solver_type",
                  "implicit_max_iters", "implicit_tolerance", "implicit_const_dt"}

# 3D defaults (used by __post_init__ when dim=3 but lists are still 2-element)
_3D_DEFAULTS = {
    "number_of_cells": [64, 128, 512],
    "lower_bound": [-20e-6, -20e-6, 0.0],
    "upper_bound": [20e-6, 20e-6, 200e-6],
    "field_bc": ["periodic", "periodic", "open"],
}


@dataclass
class LaserAccelerationSpec:
    name: str = "laser_acceleration"
    domain: DomainSpec = field(default_factory=DomainSpec)
    solver: SolverSpec = field(default_factory=SolverSpec)
    species: SpeciesSpec = field(default_factory=SpeciesSpec)
    laser: LaserSpec = field(default_factory=LaserSpec)
    diag: DiagSpec = field(default_factory=DiagSpec)
    implicit: ImplicitSolverSpec = field(default_factory=ImplicitSolverSpec)
    # AMR / resolution
    amr: AMRSpec = field(default_factory=AMRSpec)

    def __post_init__(self) -> None:
        # When dim=3 but domain list fields are still at 2D defaults,
        # silently expand them to sensible 3D defaults.
        if self.domain.dim == 3 and len(self.domain.number_of_cells) == 2:
            for attr, val in _3D_DEFAULTS.items():
                object.__setattr__(self.domain, attr, list(val))

    @classmethod
    def from_dict(cls, d: dict) -> "LaserAccelerationSpec":
        """Construct from a flat JSON dict (the backward-compatible external format)."""
        amr = AMRSpec(**{attr: d[flat] for flat, attr in _AMR_KEY_MAP.items() if flat in d})
        if "dx_target" in d and "number_of_cells" not in d:
            if "lower_bound" in d and "upper_bound" in d:
                d = dict(d)
                d["number_of_cells"] = suggest_cells(
                    d["lower_bound"], d["upper_bound"], d["dx_target"], amr.blocking_factor
                )
        domain = DomainSpec(**{k: d[k] for k in _DOMAIN_KEYS if k in d})
        solver = SolverSpec(**{k: d[k] for k in _SOLVER_KEYS if k in d})
        species = SpeciesSpec(**{k: d[k] for k in _SPECIES_KEYS if k in d})
        laser = LaserSpec(**{k: d[k] for k in _LASER_KEYS if k in d})
        diag = DiagSpec(**{k: d[k] for k in _DIAG_KEYS if k in d})
        imp_kw: dict = {}
        if "implicit_enabled" in d:     imp_kw["enabled"]     = d["implicit_enabled"]
        if "implicit_theta" in d:       imp_kw["theta"]       = d["implicit_theta"]
        if "implicit_solver_type" in d: imp_kw["solver_type"] = d["implicit_solver_type"]
        if "implicit_max_iters" in d:   imp_kw["max_iters"]   = d["implicit_max_iters"]
        if "implicit_tolerance" in d:   imp_kw["tolerance"]   = d["implicit_tolerance"]
        if "implicit_const_dt" in d:    imp_kw["const_dt"]    = d["implicit_const_dt"]
        implicit = ImplicitSolverSpec(**imp_kw)
        return cls(
            name=d.get("name", "laser_acceleration"),
            domain=domain, solver=solver, species=species, laser=laser, diag=diag,
            implicit=implicit,
            amr=amr,
        )


def generate_picmi_laser_acceleration(spec: LaserAccelerationSpec) -> str:
    """Generate a PICMI script for a simple laser acceleration setup."""

    if spec.domain.dim not in _GRID_CLASS:
        raise ValueError(f"Unsupported dim={spec.domain.dim}; must be 2 or 3")

    grid_class = _GRID_CLASS[spec.domain.dim]

    d = {
        "name": spec.name,
        "domain": asdict(spec.domain),
        "solver": asdict(spec.solver),
        "species": asdict(spec.species),
        "laser": asdict(spec.laser),
        "diag": asdict(spec.diag),
    }

    antenna_z = spec.domain.lower_bound[-1]

    script = f"""#!/usr/bin/env python3

# Auto-generated by warpx-inputgen.
import os
import sys

# Make source-tree runs work without requiring `pip install warpx`.
_this_repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir, os.pardir, os.pardir))
_pywarpx_src = os.path.join(_this_repo_root, "Python")
if _pywarpx_src not in sys.path:
    sys.path.insert(0, _pywarpx_src)

# On HPC systems where pywarpx is an editable source install but the compiled
# pybind11 extensions (.so files) live in a separate CMake install prefix,
# extend pywarpx.__path__ so that `from . import warpx_pybind_Xd` succeeds.
# Set WARPX_PYBIND_PATH to the directory containing the warpx_pybind_*.so files.
_warpx_pybind_path = os.environ.get("WARPX_PYBIND_PATH", "")
if _warpx_pybind_path and os.path.isdir(_warpx_pybind_path):
    import pywarpx as _pywarpx_pkg
    if _warpx_pybind_path not in _pywarpx_pkg.__path__:
        _pywarpx_pkg.__path__.append(_warpx_pybind_path)

from pywarpx import picmi

c = picmi.constants.c

SPEC = {d!r}

grid = picmi.{grid_class}(
    number_of_cells={spec.domain.number_of_cells!r},
    lower_bound={spec.domain.lower_bound!r},
    upper_bound={spec.domain.upper_bound!r},
    lower_boundary_conditions={spec.domain.field_bc!r},
    upper_boundary_conditions={spec.domain.field_bc!r},
)

solver = picmi.ElectromagneticSolver(grid=grid, method="CKC", cfl={spec.solver.cfl!r})

# Plasma
plasma_dist = picmi.UniformDistribution(
    density={spec.species.plasma_density!r},
    lower_bound=[None, None, {spec.species.plasma_zmin!r}],
    upper_bound=[None, None, {spec.species.plasma_zmax!r}],
    fill_in=True,
)

electrons = picmi.Species(particle_type="electron", name="electrons", initial_distribution=plasma_dist)
ions = picmi.Species(
    particle_type="H",
    name="ions",
    charge_state=1,
    initial_distribution=plasma_dist,
)

# Laser
laser = picmi.GaussianLaser(
    wavelength={spec.laser.wavelength!r},
    waist={spec.laser.waist!r},
    duration={spec.laser.duration!r},
    focal_position=[0.0, 0.0, {spec.laser.focal_position_z!r}],
    centroid_position=[0.0, 0.0, {spec.laser.centroid_position_z!r}],
    propagation_direction=[0, 0, 1],
    polarization_direction=[1, 0, 0],
    a0={spec.laser.a0!r},
    fill_in=False,
)

# Place the antenna slightly inside the domain so it's not outside due to
# floating point edge comparisons.
_antenna_z = {antenna_z!r} + 1.0e-12
antenna = picmi.LaserAntenna(position=[0.0, 0.0, _antenna_z], normal_vector=[0, 0, 1])

# Disable full field diagnostics by default in this minimal template.
# Plotfile writing from multiple MPI ranks can fail if the output directory is
# shared/contended or pre-exists from a previous run.
#
# Re-enable by adding a FieldDiagnostic and a per-run unique write_dir.
field_diag = None

sim = picmi.Simulation(
    solver=solver,
    max_steps={spec.solver.max_steps!r},
    particle_shape={spec.solver.particle_shape!r},
    warpx_use_filter=0,
)

sim.add_species(electrons, layout=picmi.GriddedLayout(grid=grid, n_macroparticle_per_cell=[2, 2, 2]))
sim.add_species(ions, layout=picmi.GriddedLayout(grid=grid, n_macroparticle_per_cell=[2, 2, 2]))

sim.add_laser(laser, injection_method=antenna)
if field_diag is not None:
    sim.add_diagnostic(field_diag)

sim.initialize_inputs()
sim.initialize_warpx()
sim.step({spec.solver.max_steps!r})
"""

    return dedent(script).lstrip()
