from __future__ import annotations

from dataclasses import asdict
from textwrap import dedent

from .spec import UniformPlasmaSpec


def _pad_to_3(vals, pad):
    """Pad a list/tuple to length 3 (WarpX expects 3-vectors for many inputs)."""
    out = list(vals)
    while len(out) < 3:
        out.append(pad)
    return out[:3]


def generate_inputs_uniform_plasma(spec: UniformPlasmaSpec) -> str:
    """Generate a native WarpX inputs file (AMReX ParmParse) for a minimal uniform plasma run.

    Note: this defaults to *plotfile* diagnostics so the resulting inputs do not
    depend on openPMD at runtime (some deployments do not ship `libopenPMD.so`).

    Important: even for 1D/2D problems, WarpX/AMReX ParmParse often expects
    3-component vectors for geometry and boundary condition parameters.
    We therefore pad to 3 components.
    """

    d = asdict(spec)  # for provenance comment

    # Pad to 3D for native inputs
    # Pad the unused dimensions with a size that is divisible by common blocking factors.
    # Many WarpX builds default to amr.blocking_factor=8.
    n_cell_3 = _pad_to_3(spec.number_of_cells, 8)
    lo_3 = _pad_to_3(spec.lower_bound, 0.0)
    hi_3 = _pad_to_3(spec.upper_bound, 1.0)
    bc_3 = _pad_to_3(spec.field_bc, "periodic")

    n_cell = " ".join(str(n) for n in n_cell_3)
    prob_lo = " ".join(f"{x:.17g}" for x in lo_3)
    prob_hi = " ".join(f"{x:.17g}" for x in hi_3)

    field_lo = " ".join(bc_3)
    field_hi = " ".join(bc_3)

    dt_lines = ""
    if spec.time_step_size is not None:
        dt_lines = f"warpx.dt = {spec.time_step_size:.17g}\n"

    # AMR: use blocking_factor=1 when max_level==0 for backward compat
    amr_bf = 1 if spec.amr_max_level == 0 else spec.amr_blocking_factor
    max_grid_size_line = ""
    if spec.warpx_max_grid_size is not None:
        max_grid_size_line = f"amr.max_grid_size = {spec.warpx_max_grid_size}\n"

    # Native diagnostics expect explicit component names (e.g. Ex Ey Ez), not group names (E, B, J).
    # Map common group shorthands to component lists.
    field_map = {
        "E": ["Ex", "Ey", "Ez"],
        "B": ["Bx", "By", "Bz"],
        # Note: J components are not always available for plotting depending on build/geometry.
        # Keep mapping but users should opt-in via spec.diag_fields.
        "J": ["Jx", "Jy", "Jz"],
    }
    fields_to_plot = []
    for f in spec.diag_fields:
        fields_to_plot.extend(field_map.get(f, [f]))

    diag_lines = dedent(
        f"""
        diagnostics.diags_names = diag1
        diag1.diag_type = Full
        diag1.intervals = {spec.diag_period}
        diag1.format = plotfile
        diag1.fields_to_plot = {' '.join(fields_to_plot)}
        """
    ).strip()

    # Particles per cell each dim: pad to 3 as well
    ppc_each_dim = " ".join(str(x) for x in _pad_to_3([1] * spec.dim, 1))

    text = f"""# Auto-generated by pywarpx.inputgen
# SPEC = {d!r}

max_step = {spec.max_steps}

amr.max_level = {spec.amr_max_level}
amr.n_cell = {n_cell}
amr.blocking_factor = {amr_bf}
{max_grid_size_line.rstrip()}

geometry.dims = 3
geometry.prob_lo = {prob_lo}
geometry.prob_hi = {prob_hi}

boundary.field_lo = {field_lo}
boundary.field_hi = {field_hi}

warpx.verbose = 1
warpx.cfl = {spec.cfl:.17g}
{dt_lines.rstrip()}

algo.particle_shape = {spec.particle_shape}
warpx.current_deposition_algo = {spec.current_deposition_algo}

particles.species_names = electrons

electrons.species_type = electron
electrons.injection_style = NUniformPerCell
electrons.num_particles_per_cell_each_dim = {ppc_each_dim}
electrons.profile = constant
electrons.density = {spec.density:.17g}
# Deterministic (zero) initial momentum to avoid requiring a momentum distribution spec
# for this minimal smoke-test.
electrons.momentum_distribution_type = constant
electrons.ux = 0.
electrons.uy = 0.
electrons.uz = 0.

{diag_lines}
"""

    return dedent(text).strip() + "\n"
